# ValPAS prototype

## Dependencies
Dependencies to run this notebook should be installed according to the README.md located at the root folder of the project.

## Jupyter notebook "frontmatter"
The following lines of code are overhead to make loading of the valpas package possible from within the notebook without having to install the package via pip / setuptools. Essentially this loads the 'src/' folder into the sys path as searchable for modules.

In [1]:
# iPython magic to autoreload modules everytime code is executed to propagate changes to the code
%load_ext autoreload
%autoreload 2

# loading '/src' into sys path
import os
import sys
module_path = os.path.abspath(os.path.join('..', 'src'))
if module_path not in sys.path:
    sys.path.append(module_path)

# don't show warnings
import warnings
warnings.filterwarnings('ignore')

### Defining the file path to the sample files:

In [2]:
# path to the csv containing the proteome data
fpath_prot = os.path.join(
    os.getcwd(),
    "..",
    "sample_data",
    "rhodo_multi_proteomics.csv"
    )

# path to the csv containing the metabolomics data
fpath_metabol = os.path.join(
    os.getcwd(),
    "..",
    "sample_data",
    "rhodo_multi_metabolomics.csv"
    )

### Correlation between samples
Correlation can be calculated between instances within one type of data (e.g. protein-protein) or between two types of data (e.g. protein-metabolite). Below both variants are demonstrated (first within one type then across types). The returned data is a series of correlated instances sorted by the strenght of their correlation.

In [3]:
# import the helper function to calculate correlations
from valpas.utils.calc_associations import calc_correlation

Here we calculate the correlation between instances within one data type. In this case the data type are protein abundances. The returned list is sorted descending (i.e. stronges correlation first).

In [4]:
import pandas as pd

df_corr_prot = calc_correlation(fpath_prot)
df_corr_prot

         RTO4_ID_1 RTO4_ID_2  Correlation
0            11652     15738     1.000000
1             9095     13762     1.000000
2            10605     16024     1.000000
3            10703     12656     1.000000
4            11694     12317     1.000000
...            ...       ...          ...
15913256     12931     13427    -0.989824
15913257     12931     13069    -0.989894
15913258     11638     12931    -0.990117
15913259     11765     12931    -0.990284
15913260     12931     13409    -0.990433

[15913261 rows x 3 columns]

Next we calculate the correlation between instances across two different types of data (in this example proteins and metabolites). Note that the function `calc_correlation` also accepts keyword parameters. If `fpath_2` is omitted as in the example above only the correlation between instances in the dataset designated by `fpath_1` is calculated. If both `fpath_1` and `fpath2` are present correlation between pairs of instances across both datasets are calculated. Additionally, note that the correlation function `corr_func` can be defined. Options are `'pearson'`, `'spearman'` and `'kendall'`. Note that if omitted the calculation defaults to `'pearson'`.

In [5]:
df_corr_prot_metabol = calc_correlation(
    fpath_1=fpath_prot,
    fpath_2=fpath_metabol,
    corr_func='spearman')
df_corr_prot_metabol

                    Metabolite RTO4_ID  Correlation
0          protocatechuic acid    8372          1.0
1        4-hydroxybenzoic acid   12651          1.0
2          protocatechuic acid   13661          1.0
3        4-hydroxybenzoic acid   12707          1.0
4        4-hydroxybenzoic acid   12704          1.0
...                        ...     ...          ...
1159293    protocatechuic acid    9705         -1.0
1159294  4-hydroxybenzoic acid   12385         -1.0
1159295    protocatechuic acid   14235         -1.0
1159296  4-hydroxybenzoic acid   12383         -1.0
1159297    protocatechuic acid   14059         -1.0

[1159298 rows x 3 columns]